# Generated by Django 5.2.17 on 2026-08-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Sales Manager'), ('sales_rep', 'Sales Representative'), ('support', 'Support')], db_index=True, default='sales_rep', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='crm_users',
        ),
    ]
