/**
 * Realistic initial mock dataset for CRM modules
 * This data powers the mock API engine when real backend is disconnected
 */

export const initialUsers = [
  {
    id: 'usr-101',
    name: 'Sarah Connor',
    email: 'sarah.connor@apexcrm.io',
    username: 'sarah_admin',
    role: 'Admin',
    status: 'Active',
    department: 'Management',
    phone: '+1 (555) 234-5678',
    avatar: '',
    createdAt: '2024-01-15T09:00:00Z',
    lastLogin: '2024-03-10T14:22:00Z',
  },
  {
    id: 'usr-102',
    name: 'Alex Rivera',
    email: 'alex.rivera@apexcrm.io',
    username: 'alex_manager',
    role: 'Manager',
    status: 'Active',
    department: 'Sales',
    phone: '+1 (555) 345-6789',
    avatar: '',
    createdAt: '2024-01-20T10:30:00Z',
    lastLogin: '2024-03-09T18:05:00Z',
  },
  {
    id: 'usr-103',
    name: 'Jessica Chen',
    email: 'jessica.chen@apexcrm.io',
    username: 'jessica_sales',
    role: 'Manager',
    status: 'Active',
    department: 'Sales',
    phone: '+1 (555) 456-7890',
    avatar: '',
    createdAt: '2024-02-01T11:15:00Z',
    lastLogin: '2024-03-10T09:12:00Z',
  },
  {
    id: 'usr-104',
    name: 'Marcus Vance',
    email: 'marcus.v@apexcrm.io',
    username: 'marcus_support',
    role: 'Manager',
    status: 'Active',
    department: 'Customer Support',
    phone: '+1 (555) 567-8901',
    avatar: '',
    createdAt: '2024-02-10T08:45:00Z',
    lastLogin: '2024-03-08T16:40:00Z',
  },
  {
    id: 'usr-105',
    name: 'Elena Rostova',
    email: 'elena.r@apexcrm.io',
    username: 'elena_sales',
    role: 'Manager',
    status: 'Inactive',
    department: 'Marketing',
    phone: '+1 (555) 678-9012',
    avatar: '',
    createdAt: '2023-11-12T14:00:00Z',
    lastLogin: '2024-01-05T12:00:00Z',
  },
];

export const initialCustomers = [
  {
    id: 'cust-201',
    companyName: 'Acme Global Corp',
    contactPerson: 'David Miller',
    email: 'dmiller@acmeglobal.com',
    phone: '+1 (555) 789-0123',
    stage: 'Active',
    industry: 'Enterprise Software',
    dealValue: 48500,
    assignedTo: 'Alex Rivera',
    assignedToId: 'usr-102',
    city: 'New York, USA',
    createdAt: '2024-01-18T10:00:00Z',
  },
  {
    id: 'cust-202',
    companyName: 'Nova FinTech Solutions',
    contactPerson: 'Sophia Reynolds',
    email: 's.reynolds@novafintech.io',
    phone: '+1 (555) 890-1234',
    stage: 'Active',
    industry: 'Financial Technology',
    dealValue: 72000,
    assignedTo: 'Sarah Connor',
    assignedToId: 'usr-101',
    city: 'San Francisco, USA',
    createdAt: '2024-01-22T14:30:00Z',
  },
  {
    id: 'cust-203',
    companyName: 'BlueSky Logistics',
    contactPerson: 'Robert Sterling',
    email: 'sterling@blueskylogistics.com',
    phone: '+1 (555) 901-2345',
    stage: 'Pending',
    industry: 'Supply Chain & Freight',
    dealValue: 26000,
    assignedTo: 'Jessica Chen',
    assignedToId: 'usr-103',
    city: 'Chicago, USA',
    createdAt: '2024-02-05T09:15:00Z',
  },
  {
    id: 'cust-204',
    companyName: 'Zenith Health Systems',
    contactPerson: 'Dr. Evelyn Carter',
    email: 'ecarter@zenithhealth.org',
    phone: '+1 (555) 012-3456',
    stage: 'Active',
    industry: 'Healthcare Services',
    dealValue: 115000,
    assignedTo: 'Alex Rivera',
    assignedToId: 'usr-102',
    city: 'Boston, USA',
    createdAt: '2024-02-14T11:45:00Z',
  },
  {
    id: 'cust-205',
    companyName: 'Vanguard Retailers Ltd',
    contactPerson: 'Michael Chang',
    email: 'mchang@vanguardretail.com',
    phone: '+1 (555) 123-4567',
    stage: 'Inactive',
    industry: 'E-commerce & Retail',
    dealValue: 14200,
    assignedTo: 'Marcus Vance',
    assignedToId: 'usr-104',
    city: 'Austin, USA',
    createdAt: '2023-12-01T15:20:00Z',
  },
];

export const initialLeads = [
  {
    id: 'lead-301',
    name: 'CloudScale Technologies',
    contactName: 'Brian Taylor',
    email: 'btaylor@cloudscale.net',
    phone: '+1 (555) 321-9876',
    source: 'Website',
    status: 'Qualified',
    estimatedValue: 34000,
    assignedTo: 'Jessica Chen',
    score: 85,
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'lead-302',
    name: 'Apex Bio Labs',
    contactName: 'Karen White',
    email: 'kwhite@apexbio.org',
    phone: '+1 (555) 654-3210',
    source: 'Referral',
    status: 'Proposal',
    estimatedValue: 52000,
    assignedTo: 'Alex Rivera',
    score: 92,
    createdAt: '2024-03-03T11:20:00Z',
  },
  {
    id: 'lead-303',
    name: 'Pulse Marketing Agency',
    contactName: 'Daniel Green',
    email: 'dgreen@pulsemktg.co',
    phone: '+1 (555) 987-6543',
    source: 'LinkedIn',
    status: 'Contacted',
    estimatedValue: 18500,
    assignedTo: 'Jessica Chen',
    score: 64,
    createdAt: '2024-03-05T16:45:00Z',
  },
  {
    id: 'lead-304',
    name: 'Nexus Security Infra',
    contactName: 'Liam Patterson',
    email: 'liam@nexusinfra.io',
    phone: '+1 (555) 876-5432',
    source: 'Cold Call',
    status: 'New',
    estimatedValue: 41000,
    assignedTo: 'Sarah Connor',
    score: 50,
    createdAt: '2024-03-08T09:30:00Z',
  },
  {
    id: 'lead-305',
    name: 'Orbit Media House',
    contactName: 'Chloe Bennett',
    email: 'cbennett@orbitmedia.com',
    phone: '+1 (555) 765-4321',
    source: 'Website',
    status: 'Lost',
    estimatedValue: 9800,
    assignedTo: 'Marcus Vance',
    score: 30,
    createdAt: '2024-02-25T14:10:00Z',
  },
];

export const initialTasks = [
  {
    id: 'task-401',
    title: 'Conduct product demo for Acme Global',
    description: 'Walkthrough the enterprise CRM reporting and REST API sync module.',
    dueDate: '2024-03-15',
    priority: 'High',
    status: 'Pending',
    assignedTo: 'Alex Rivera',
    assignedToId: 'usr-102',
    category: 'Sales',
  },
  {
    id: 'task-402',
    title: 'Follow up on Apex Bio Labs contract proposal',
    description: 'Check if the legal team has cleared the Master Services Agreement.',
    dueDate: '2024-03-12',
    priority: 'High',
    status: 'In Progress',
    assignedTo: 'Jessica Chen',
    assignedToId: 'usr-103',
    category: 'Sales',
  },
  {
    id: 'task-403',
    title: 'Review Q1 CRM pipeline and quarterly revenue',
    description: 'Prepare executive deck on churn rates and conversion metrics.',
    dueDate: '2024-03-20',
    priority: 'Medium',
    status: 'Pending',
    assignedTo: 'Sarah Connor',
    assignedToId: 'usr-101',
    category: 'Management',
  },
  {
    id: 'task-404',
    title: 'Onboard Nova FinTech tech team',
    description: 'Deliver webhook setup documentation and API access tokens.',
    dueDate: '2024-03-08',
    priority: 'Medium',
    status: 'Completed',
    assignedTo: 'Marcus Vance',
    assignedToId: 'usr-104',
    category: 'Support',
  },
  {
    id: 'task-405',
    title: 'Resolve support ticket #1049 for BlueSky Logistics',
    description: 'Check contact sync discrepancy in billing address.',
    dueDate: '2024-03-11',
    priority: 'Low',
    status: 'Completed',
    assignedTo: 'Marcus Vance',
    assignedToId: 'usr-104',
    category: 'Support',
  },
];

export const initialActivities = [
  {
    id: 'act-501',
    user: 'Alex Rivera',
    action: 'updated customer stage to Active for',
    target: 'Nova FinTech Solutions',
    timestamp: '2024-03-10T11:30:00Z',
    type: 'customer',
  },
  {
    id: 'act-502',
    user: 'Jessica Chen',
    action: 'created a new qualified lead',
    target: 'CloudScale Technologies',
    timestamp: '2024-03-10T09:45:00Z',
    type: 'lead',
  },
  {
    id: 'act-503',
    user: 'Sarah Connor',
    action: 'scheduled executive review task',
    target: 'Review Q1 CRM pipeline',
    timestamp: '2024-03-09T16:15:00Z',
    type: 'task',
  },
  {
    id: 'act-504',
    user: 'Marcus Vance',
    action: 'completed onboarding support for',
    target: 'Zenith Health Systems',
    timestamp: '2024-03-09T14:00:00Z',
    type: 'support',
  },
  {
    id: 'act-505',
    user: 'Alex Rivera',
    action: 'added new customer record',
    target: 'BlueSky Logistics',
    timestamp: '2024-03-08T17:20:00Z',
    type: 'customer',
  },
];

export const initialProducts = [
  {
    id: 'prod-001',
    code: 'PLSTS-CRM-ENT',
    name: 'Enterprise CRM Core Platform',
    category: 'Software License',
    unitPrice: 75000,
    taxPercentage: 18,
    status: 'Active',
    description: 'Complete centralized CRM system with admin, sales, and employee portals.',
  },
  {
    id: 'prod-002',
    code: 'PLSTS-API-SYNC',
    name: 'REST API & Payment Gateway Integration',
    category: 'Implementation',
    unitPrice: 25000,
    taxPercentage: 18,
    status: 'Active',
    description: 'Custom webhook and REST API synchronizer for ERP and accounting software.',
  },
  {
    id: 'prod-003',
    code: 'PLSTS-CLOUD-HOST',
    name: 'Cloud VPS Setup & Managed Hosting',
    category: 'Infrastructure',
    unitPrice: 18000,
    taxPercentage: 18,
    status: 'Active',
    description: 'Dedicated high-availability server setup with automated daily backups & SSL.',
  },
  {
    id: 'prod-004',
    code: 'PLSTS-SLA-ANNUAL',
    name: 'Annual Maintenance & Support SLA',
    category: 'Service Contract',
    unitPrice: 30000,
    taxPercentage: 18,
    status: 'Active',
    description: '24/7 technical monitoring, bug patches, and version upgrades.',
  },
  {
    id: 'prod-005',
    code: 'PLSTS-CUSTOM-DEV',
    name: 'Custom Module Development (per sprint)',
    category: 'Professional Services',
    unitPrice: 40000,
    taxPercentage: 18,
    status: 'Active',
    description: 'Bespoke workflow engineering tailored to specific client industry requirements.',
  },
];

export const initialOpportunities = [
  {
    id: 'opp-001',
    title: 'Acme Corp ERP & CRM Modernization',
    customerId: 'cust-201',
    customerName: 'Acme Global Corp',
    contactPerson: 'David Miller',
    stage: 'Proposal',
    dealValue: 120000,
    probability: 75,
    expectedCloseDate: '2026-09-30',
    assignedTo: 'Alex Rivera',
    status: 'Open',
    notes: 'Client reviewed quotation v1.0, negotiating SLA terms.',
  },
  {
    id: 'opp-002',
    title: 'Nova FinTech Lead Automation Suite',
    customerId: 'cust-202',
    customerName: 'Nova FinTech Solutions',
    contactPerson: 'Sophia Reynolds',
    stage: 'Negotiation',
    dealValue: 95000,
    probability: 85,
    expectedCloseDate: '2026-09-25',
    assignedTo: 'Sarah Connor',
    status: 'Open',
    notes: 'Legal approved DPA. Awaiting final PO approval from CFO.',
  },
  {
    id: 'opp-003',
    title: 'BlueSky Logistics Tracking Integration',
    customerId: 'cust-203',
    customerName: 'BlueSky Logistics',
    contactPerson: 'Robert Sterling',
    stage: 'Qualification',
    dealValue: 45000,
    probability: 50,
    expectedCloseDate: '2026-10-15',
    assignedTo: 'Jessica Chen',
    status: 'Open',
    notes: 'Discovery workshop scheduled for next Tuesday.',
  },
  {
    id: 'opp-004',
    title: 'Zenith Health Systems Patient CRM',
    customerId: 'cust-204',
    customerName: 'Zenith Health Systems',
    contactPerson: 'Dr. Evelyn Carter',
    stage: 'Closed Won',
    dealValue: 155000,
    probability: 100,
    expectedCloseDate: '2026-08-30',
    assignedTo: 'Alex Rivera',
    status: 'Won',
    notes: 'Deal signed. Implementation phase underway.',
  },
];

export const initialFollowUps = [
  {
    id: 'flw-001',
    title: 'Follow-up on Quotation QT-2026-001 Terms',
    entityType: 'Customer',
    entityName: 'Acme Global Corp',
    contactPerson: 'David Miller',
    type: 'Call',
    scheduledDate: '2026-09-12T14:30',
    assignedTo: 'Alex Rivera',
    status: 'Pending',
    notes: 'Check if board cleared budget allocation for CRM customization.',
  },
  {
    id: 'flw-002',
    title: 'Demonstration meeting for Product Catalog',
    entityType: 'Lead',
    entityName: 'CloudScale Technologies',
    contactPerson: 'Brian Taylor',
    type: 'Meeting',
    scheduledDate: '2026-09-14T11:00',
    assignedTo: 'Jessica Chen',
    status: 'Pending',
    notes: 'Present REST API endpoints and quote generation workflow.',
  },
  {
    id: 'flw-003',
    title: 'Post-delivery review call',
    entityType: 'Customer',
    entityName: 'Zenith Health Systems',
    contactPerson: 'Dr. Evelyn Carter',
    type: 'Call',
    scheduledDate: '2026-09-05T10:00',
    assignedTo: 'Alex Rivera',
    status: 'Completed',
    notes: 'Client expressed satisfaction with phase 1 migration.',
  },
];

export const initialQuotations = [
  {
    id: 'quot-001',
    quotationNumber: 'PLSTS/CRM/2026/001',
    version: 'v1.0',
    customerId: 'cust-201',
    customerName: 'Acme Global Corp',
    contactPerson: 'David Miller',
    email: 'dmiller@acmeglobal.com',
    phone: '+1 (555) 789-0123',
    address: '100 Broadway, New York, USA',
    createdDate: '2026-08-18',
    validUntil: '2026-09-18',
    status: 'Sent',
    assignedTo: 'Alex Rivera',
    items: [
      {
        productId: 'prod-001',
        name: 'Enterprise CRM Core Platform',
        description: 'Complete centralized CRM system with admin, sales, and employee portals.',
        quantity: 1,
        unitPrice: 75000,
        discountPercentage: 5,
        taxPercentage: 18,
        lineTotal: 84075,
      },
      {
        productId: 'prod-002',
        name: 'REST API & Payment Gateway Integration',
        description: 'Custom webhook and REST API synchronizer.',
        quantity: 1,
        unitPrice: 25000,
        discountPercentage: 0,
        taxPercentage: 18,
        lineTotal: 29500,
      },
    ],
    subtotal: 96250,
    discountTotal: 3750,
    taxTotal: 17325,
    grandTotal: 113575,
    terms: '1. 50% advance along with work order.\n2. 30% upon UAT deployment.\n3. 20% upon final sign-off.\n4. Standard 1 year warranty included.',
  },
  {
    id: 'quot-002',
    quotationNumber: 'PLSTS/CRM/2026/002',
    version: 'v1.1',
    customerId: 'cust-202',
    customerName: 'Nova FinTech Solutions',
    contactPerson: 'Sophia Reynolds',
    email: 's.reynolds@novafintech.io',
    phone: '+1 (555) 890-1234',
    address: '456 Market St, San Francisco, USA',
    createdDate: '2026-08-25',
    validUntil: '2026-09-25',
    status: 'Accepted',
    assignedTo: 'Sarah Connor',
    items: [
      {
        productId: 'prod-001',
        name: 'Enterprise CRM Core Platform',
        description: 'Multi-tenant cloud architecture',
        quantity: 1,
        unitPrice: 75000,
        discountPercentage: 10,
        taxPercentage: 18,
        lineTotal: 79650,
      },
      {
        productId: 'prod-004',
        name: 'Annual Maintenance & Support SLA',
        description: '24/7 dedicated response SLA',
        quantity: 1,
        unitPrice: 30000,
        discountPercentage: 0,
        taxPercentage: 18,
        lineTotal: 35400,
      },
    ],
    subtotal: 97500,
    discountTotal: 7500,
    taxTotal: 17550,
    grandTotal: 115050,
    terms: 'Payment terms: 30 days net from invoice date.',
  },
];

export const initialNotifications = [
  {
    id: 'notif-001',
    title: 'Pending Follow-up Reminder',
    message: 'Follow-up call with David Miller (Acme Corp) is due today.',
    time: '15m ago',
    type: 'followup',
    read: false,
    link: '/follow-ups',
  },
  {
    id: 'notif-002',
    title: 'Quotation Accepted 🎉',
    message: 'Nova FinTech accepted quotation PLSTS/CRM/2026/002 ($115,050).',
    time: '2h ago',
    type: 'quotation',
    read: false,
    link: '/quotations',
  },
  {
    id: 'notif-003',
    title: 'New Hot Lead Assigned',
    message: 'Lead "Nexus Security Infra" assigned to Sarah Connor.',
    time: '4h ago',
    type: 'lead',
    read: true,
    link: '/leads',
  },
  {
    id: 'notif-004',
    title: 'High Priority Task Due Soon',
    message: 'Conduct product demo for Acme Global is due tomorrow.',
    time: '1d ago',
    type: 'task',
    read: true,
    link: '/tasks',
  },
];
