# Generated by Django 5.2.17 on 2026-09-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_task_completed_at_task_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='Sales', max_length=100, null=True),
        ),
    ]
