# Generated by Django 5.2.17 on 2026-09-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options_customer_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primary Contact Person'),
        ),
    ]
