# Generated by Django 5.2.17 on 2026-09-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deal_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Contract Deal Value'),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
