# Generated by Django 5.2.17 on 2026-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='parameters',
        ),
        migrations.AddField(
            model_name='savedreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='filters_json',
            field=models.JSONField(blank=True, default=dict, help_text='Saved filter parameters in JSON format'),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, shared across all sales managers'),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='report_type',
            field=models.CharField(choices=[('lead_conversion', 'Lead Conversion Analytics'), ('sales_pipeline', 'Sales Pipeline & Revenue Forecast'), ('employee_performance', 'Employee Performance Leaderboard'), ('customer_retention', 'Customer Retention & Touchpoints'), ('custom', 'Custom Filtered Report')], default='sales_pipeline', max_length=30),
        ),
        migrations.AlterModelTable(
            name='savedreport',
            table='crm_saved_reports',
        ),
    ]
