# Generated by Django 5.2.17 on 2026-09-02 04:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_product_tax_rate_and_more'),
        ('quotations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='total',
        ),
        migrations.AddField(
            model_name='quotation',
            name='grand_total',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='1. Quotation valid for 30 days.\n2. Payment terms: 50% advance, 50% upon delivery.', null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterModelTable(
            name='quotation',
            table='crm_quotations',
        ),
        migrations.AlterModelTable(
            name='quotationitem',
            table='crm_quotation_items',
        ),
    ]
