# Generated by Django 5.2.17 on 2026-09-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
