# Generated by Django 5.2.17 on 2026-09-01 12:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='actual_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_reason',
            field=models.TextField(blank=True, help_text='Required when stage is changed to Closed Lost', null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expected_close_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.PositiveIntegerField(default=20, help_text='Estimated win probability percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('discovery', 'Discovery & Needs Analysis'), ('proposal', 'Proposal / Quote Sent'), ('negotiation', 'In Negotiation'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], db_index=True, default='discovery', max_length=30),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterModelTable(
            name='opportunity',
            table='crm_opportunities',
        ),
    ]
