# Generated by Django 5.2.17 on 2026-08-31 10:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('software', 'Software & Licenses'), ('hardware', 'Hardware & Equipment'), ('service', 'Professional Services'), ('subscription', 'Recurring Subscription'), ('maintenance', 'Support & Maintenance'), ('other', 'Other')], default='software', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST / Tax percentage (e.g. 18.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Product Code / SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Base selling price before tax', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterModelTable(
            name='product',
            table='crm_products',
        ),
    ]
